# Cria a tabuada de 1 à 10 do número digitado

t = int(input('Digite um valor para descobrir a tabuada: '))
print('-' * 12)
print('{} x 1 ='.format(t), t * 1)
print('{} x 2 ='.format(t), t * 2)
print('{} x 3 ='.format(t), t * 3)
print('{} x 4 ='.format(t), t * 4)
print('{} x 5 ='.format(t), t * 5)
print('{} x 6 ='.format(t), t * 6)
print('{} x 7 ='.format(t), t * 7)
print('{} x 8 ='.format(t), t * 8)
print('{} x 9 ='.format(t), t * 9)
print('{} x 10 ='.format(t), t * 10)
print('-' * 12)
